### ISSUE TITLE
Markdown笔记图片缺失

### ISSUE THREAD

**Issue by YuruiHong** [chillcicada/MySchoolwork#1]
是不是所有的`assets`文件夹都忘记上传了？（🐶

**Comment by chillcicada** [comment]
> 是不是所有的`assets`文件夹都忘记上传了？（🐶

.gitignore 里面写了暂时把 assets 等二进制资源限制了，图片的话还有一部分没有 webp 化，未来打算把这部分迁移到 cdn 上面🥲
